### ISSUE TITLE
get error when use in pytest-6.2.2

### ISSUE THREAD

**Issue by 15klli** [LaserPhaser/pytest-collect-formatter#2]
![image](https://user-images.githubusercontent.com/17797189/112446532-460a9000-8d8b-11eb-862b-003522dea0f5.png)
the plugin is loaded but get error

**Comment by 15klli** [comment]
https://pypi.org/project/pytest-collect-formatter/

the demo from the above website is wrong
the right way to use is like the following that contains `=`
```bash
pytest --co --collect-output-file=k.json --collect-format=json
```

**Comment by LaserPhaser** [comment]
@15klli Sorry, my fault, will fix the docs
